spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BankManagementServiceDB
    username: pguser
    password: 9E2dc34A2

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 30

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB